### ISSUE TITLE
blockapss: distiguising functions calls and transfers

### ISSUE THREAD

**Issue by Firescar96** [blockapps/hserver-eth#30]
When i send ether to an account using the blockapps api (specifically lightwalled) it appears on http://blockapps.net/demo/ as a function call instead of an ether transfer.

Of course the money ends up in the right place which is what matters, but still.

**Comment by jamshidh** [comment]
I think this might be a duplicate of https://github.com/blockapps/hserver-eth/issues/14.

If I am correct, can you remark that here, and close this bug....

**Comment by kejace** [comment]
I think demo is deprecated. Closing.
